version: "3.9"

services:
    front:
        container_name: front
        build:
            context: .docker/development/node
        volumes:
            - ./:/app
        tty: true
        hostname: front
        ports:
            - "80:80"
        command: yarn serve
        networks:
            - front

networks:
    front:
        name: front
